#############################################################################
# Makefile for building: diglet
# Generated by qmake (2.01a) (Qt 4.8.3) on: mar jun 4 00:01:36 2013
# Project:  diglet.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile diglet.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src-principalserver \
		sub-src-clientcpp \
		sub-src-lss

src/principalserver//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/principalserver/ || $(MKDIR) src/principalserver/ 
	cd src/principalserver/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/principalserver/principalserver.pro -o $(MAKEFILE)
sub-src-principalserver-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/principalserver/ || $(MKDIR) src/principalserver/ 
	cd src/principalserver/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/principalserver/principalserver.pro -o $(MAKEFILE)
sub-src-principalserver: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE)
sub-src-principalserver-make_default: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) 
sub-src-principalserver-make_first: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) first
sub-src-principalserver-all: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) all
sub-src-principalserver-clean: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-principalserver-distclean: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-principalserver-install_subtargets: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) install
sub-src-principalserver-uninstall_subtargets: src/principalserver//$(MAKEFILE) FORCE
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) uninstall
src/clientcpp//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/clientcpp/ || $(MKDIR) src/clientcpp/ 
	cd src/clientcpp/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/clientcpp/clientcpp.pro -o $(MAKEFILE)
sub-src-clientcpp-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/clientcpp/ || $(MKDIR) src/clientcpp/ 
	cd src/clientcpp/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/clientcpp/clientcpp.pro -o $(MAKEFILE)
sub-src-clientcpp: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE)
sub-src-clientcpp-make_default: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) 
sub-src-clientcpp-make_first: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) first
sub-src-clientcpp-all: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clientcpp-clean: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clientcpp-distclean: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-clientcpp-install_subtargets: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) install
sub-src-clientcpp-uninstall_subtargets: src/clientcpp//$(MAKEFILE) FORCE
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) uninstall
src/lss//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/lss/ || $(MKDIR) src/lss/ 
	cd src/lss/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/lss/lss.pro -o $(MAKEFILE)
sub-src-lss-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/lss/ || $(MKDIR) src/lss/ 
	cd src/lss/ && $(QMAKE) /home/maikol/Documentos/C++/diglet/src/lss/lss.pro -o $(MAKEFILE)
sub-src-lss: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE)
sub-src-lss-make_default: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) 
sub-src-lss-make_first: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) first
sub-src-lss-all: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) all
sub-src-lss-clean: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-lss-distclean: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-lss-install_subtargets: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) install
sub-src-lss-uninstall_subtargets: src/lss//$(MAKEFILE) FORCE
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: diglet.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile diglet.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile diglet.pro

qmake_all: sub-src-principalserver-qmake_all sub-src-clientcpp-qmake_all sub-src-lss-qmake_all FORCE

make_default: sub-src-principalserver-make_default sub-src-clientcpp-make_default sub-src-lss-make_default FORCE
make_first: sub-src-principalserver-make_first sub-src-clientcpp-make_first sub-src-lss-make_first FORCE
all: sub-src-principalserver-all sub-src-clientcpp-all sub-src-lss-all FORCE
clean: sub-src-principalserver-clean sub-src-clientcpp-clean sub-src-lss-clean FORCE
distclean: sub-src-principalserver-distclean sub-src-clientcpp-distclean sub-src-lss-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-principalserver-install_subtargets sub-src-clientcpp-install_subtargets sub-src-lss-install_subtargets FORCE
uninstall_subtargets: sub-src-principalserver-uninstall_subtargets sub-src-clientcpp-uninstall_subtargets sub-src-lss-uninstall_subtargets FORCE

sub-src-principalserver-check: src/principalserver/$(MAKEFILE)
	cd src/principalserver/ && $(MAKE) -f $(MAKEFILE) check
sub-src-clientcpp-check: src/clientcpp/$(MAKEFILE)
	cd src/clientcpp/ && $(MAKE) -f $(MAKEFILE) check
sub-src-lss-check: src/lss/$(MAKEFILE)
	cd src/lss/ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-principalserver-check sub-src-clientcpp-check sub-src-lss-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

