all:

	g++ -std=c++11 -pthread main.cpp lss.cpp lssconsole.cpp lssmanager.cpp lssnetworkhandler.cpp lssoperations.cpp ../structures/simplelist/simplelist.cpp ../structures/simplelist/node.cpp ../tokenizer/tokenizer.cpp ../networkhandler/networkhandler.cpp ../binaryoperations/baseconverter.cpp ../binaryoperations/byteshandler.cpp ../md5/md5.cpp -o main
